"""add phone_otp table

Revision ID: 65b4d8c9356a
Revises: bdfa9a95bab2
Create Date: 2025-08-21 18:18:37.994763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '65b4d8c9356a'
down_revision: Union[str, Sequence[str], None] = 'bdfa9a95bab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_otp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts_left', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_phone_otp_user')
    )
    op.create_index(op.f('ix_phone_otp_expires_at'), 'phone_otp', ['expires_at'], unique=False)
    op.create_index(op.f('ix_phone_otp_user_id'), 'phone_otp', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_otp_user_id'), table_name='phone_otp')
    op.drop_index(op.f('ix_phone_otp_expires_at'), table_name='phone_otp')
    op.drop_table('phone_otp')
    # ### end Alembic commands ###
