"""products: JSON nutritional_value + package(text)

Revision ID: bdfa9a95bab2
Revises: fc6b336f833f
Create Date: 2025-08-20 21:36:07.020335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdfa9a95bab2'
down_revision: Union[str, Sequence[str], None] = 'fc6b336f833f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('nutritional', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('package', sa.Text(), nullable=True))
    op.drop_column('products', 'nutritional_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('nutritional_value', sa.TEXT(), nullable=True))
    op.drop_column('products', 'package')
    op.drop_column('products', 'nutritional')
    # ### end Alembic commands ###
